# Generated by Django 3.0.5 on 2021-03-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='title',
            name='rating',
        ),
        migrations.AddField(
            model_name='user',
            name='is_code_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
