# Generated by Django 3.0.5 on 2021-04-03 13:44

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210402_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.IntegerField(blank=True, null=True, validators=[api.validators.year_validator], verbose_name='Год выпуска'),
        ),
    ]
